### ISSUE TITLE
Which version of `libigl` does the code dependent on

### ISSUE THREAD

**Issue by jiangzhongshi** [Roipo/Autocuts#2]
Hi Roi,

I am trying to migrate the code to cross-platform (macOS and Linux), to use in my current project. That's why I am bugging you again.

It seems that you are using `multi-mesh-viewer` branch from `schuellc`, but I don't find some of the interface, notably in file `SolverPlugin.cpp` line 123: `tex_col1`. Can you point out to me the commit and version of libigl you are using? That'll be great help!

Thanks,
Zhongshi

**Comment by Roipo** [comment]
I added a the specific libigl commit as submodule.
